# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca26c0194fe0450df69392a853f2bf9615a7ae3c02f9814abf0a79ff7ab8d414c9e0e5406c07fc082aa0deb36d4143cb66ec92c25cda42b6640131b4998cfc62

test:
  secret_key_base: 67a4acd15ea4eadb9bde7d2bcaf298ecc85df86606da5658b915da523f4359c9f0badb20e089af46a936913b7b41c3d9f6034b8173da1ad9a0df1c9aa6d43284

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
